##8.3

###ex12

In [1]:
def factors(n):
  return [i for i in range(1,n+1) if n % i == 0]
def primes(n):
  prime = []
  for i in range(1,n):
    for j in range(2,i):
      if i % j == 0 :
        break
    else:
      prime.append(i)
  return prime

####a

In [2]:
import math_module1
print(math_module1.factors(50))

[1, 2, 5, 10, 25, 50]


In [3]:
print(math_module1.primes(100))

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


####b

In [4]:
import sys
my_pkg = '/content/drive/MyDrive/113-1程式設計/python_pkg/my_pkg'
if my_pkg not in sys.path:
  sys.path.append(my_pkg)

In [5]:
import math_module2 as math2
math2.factors(50)

[1, 2, 5, 10, 25, 50]

In [6]:
print(math2.primes(100))

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


###ex13

In [7]:
import m1
def is_primes(p):
  return True if len(m1.factors(p)) == 2 else False

In [8]:
import m2
m2.is_primes(50)

False

In [9]:
m2.is_primes(17)

True

##9.1

In [10]:
import numpy as np

###ex1

####a

In [11]:
a = np.array([[1.2],[4.3],[5.4],[6.7]])
print('形狀:',a.shape)
print('維度:',a.ndim)
print('大小:',a.size)

形狀: (4, 1)
維度: 2
大小: 4


####b

In [12]:
a = np.array([[1.2,4.3,5.4,6.7]])
print('形狀:',a.shape)
print('維度:',a.ndim)
print('大小:',a.size)

形狀: (1, 4)
維度: 2
大小: 4


####c

In [13]:
a = np.array([[5]])
print('形狀:',a.shape)
print('維度:',a.ndim)
print('大小:',a.size)

形狀: (1, 1)
維度: 2
大小: 1


####d

In [14]:
np.array([[4,4,4,4],[2,2,2,2],[5,5,5,5]])

array([[4, 4, 4, 4],
       [2, 2, 2, 2],
       [5, 5, 5, 5]])

###ex2

####a

In [15]:
np.array([[4,7],[8,12]])

array([[ 4,  7],
       [ 8, 12]])

####b

In [16]:
np.array([[7.4],[6.7],[2.0]])

array([[7.4],
       [6.7],
       [2. ]])

####c

In [17]:
np.array([[7,4],[6,7],[9,-5]])

array([[ 7,  4],
       [ 6,  7],
       [ 9, -5]])

####d

In [18]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

####ex3

In [19]:
np.array([[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],
          [[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]]])

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

###ex4

In [20]:
np.array(5).ndim ##因為她有建立一個0維度的陣列可以查詢維度

0

In [21]:
#5.ndim  ##無法對整數查詢維度

###ex5

In [22]:
np.arange(0,1.001,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

###ex6

In [23]:
np.zeros((2,3,4),dtype='uint8')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

###ex7

In [24]:
np.random.uniform(-1,1,(2,3))

array([[-0.80519332,  0.30457184,  0.07048522],
       [-0.62296661, -0.44925906,  0.38680941]])

###ex8

In [25]:
np.random.choice(np.arange(1, 21), size=10, replace=False)

array([ 3, 17,  2,  6,  5, 12,  9, 19, 11,  4])

###ex9

In [26]:
a = np.array([[0,1,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
rg=np.random.default_rng(999)

####a

In [27]:
rg.choice(a.flatten(),size=8,replace=False)

array([ 1, 10, 11,  7,  3, 14, 12,  8])

####b

In [28]:
rg.choice(a.flatten(),size=10)

array([10,  9, 14,  9,  3,  0,  9, 15, 10,  5])

####c

In [29]:
rg.choice(a,size=2,axis=0,replace=False)

array([[ 6,  7,  8,  9, 10],
       [ 0,  1,  3,  4,  5]])

In [30]:
rg.permutation(a,axis=1)

array([[ 4,  1,  3,  5,  0],
       [ 9,  7,  8, 10,  6],
       [14, 12, 13, 15, 11]])