##9.2

In [1]:
import numpy as np

###ex10

In [2]:
a = np.array([23, 67, 54, 26, 92, 88, 53])

####a

In [3]:
a[[0,2,5]]

array([23, 54, 88])

####b

In [4]:
a[-3:]

array([92, 88, 53])

####c

In [5]:
a[a > 50]

array([67, 54, 92, 88, 53])

####d

In [6]:
a[a % 2 == 1]

array([23, 67, 53])

####e

In [7]:
a[a % 2 == 0]

array([54, 26, 92, 88])

####f

In [8]:
a[::-1]

array([53, 88, 92, 26, 54, 67, 23])

####g

In [9]:
a[4:2:-1]

array([92, 26])

###ex11

In [10]:
a = np.arange(20).reshape((4, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

####a

In [11]:
a[0:2,1:3]

array([[1, 2],
       [6, 7]])

####b

In [12]:
a[:,[2,4]]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

####c

In [13]:
a[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

####d

In [14]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

####e

In [15]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])

####f

In [16]:
[a[i,j] for i in range(a.shape[0]) for j in range(a.shape[1]) if (i + j) % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

####g

In [17]:
a[(a%2==0) & (a%3!=0)].size

6

###ex12

In [18]:
a=np.array([38, 43, 21, 87, 92, 55, 40, 63])

####a

In [19]:
a[[2,2,3,3]]

array([21, 21, 87, 87])

####b

In [20]:
a[[[2,2,3,3]]]

array([[21, 21, 87, 87]])

####c

In [21]:
a[[[2],[2],[3],[3]]]

array([[21],
       [21],
       [87],
       [87]])

####d

In [22]:
a[[[2,4,4],[3,1,0]]]

array([[21, 92, 92],
       [87, 43, 38]])

####e

In [23]:
a[[[2,4],[3,1],[-3,3]]]

array([[21, 92],
       [87, 43],
       [55, 87]])

####f

In [24]:
a[[[0,-1]]*3]

array([[38, 63],
       [38, 63],
       [38, 63]])

###ex13

In [25]:
a=np.arange(10,30).reshape(4,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

####a

In [26]:
a[[1,2],[2,3]]

array([17, 23])

####b

In [27]:
a[[0,1,2],[0,1,3]]

array([10, 16, 23])

####c

In [28]:
a[[0,2,3],3:]

array([[13, 14],
       [23, 24],
       [28, 29]])

####d

In [29]:
a[2:,[0,2,3]]

array([[20, 22, 23],
       [25, 27, 28]])

####e

In [30]:
a[[0,2],:][:,[0,2]]

array([[10, 12],
       [20, 22]])

####f

In [31]:
a[:2,[1,3,4]]

array([[11, 13, 14],
       [16, 18, 19]])

###ex14

In [32]:
a=np.array([0,1,2,3,4,5])

####a

In [33]:
b=a[3:] #view
np.may_share_memory(a,b)

True

####b

In [34]:
b=a[::-1] #view
np.may_share_memory(a,b)

True

####c

In [35]:
b=a.reshape(2,3)  #view
np.may_share_memory(a,b)

True

####d

In [36]:
b=np.random.permutation(a) #copy
np.may_share_memory(a,b)

False

####e

In [37]:
b=a[[0,3,4]] #copy
np.may_share_memory(a,b)

False

####f

In [38]:
b=a[1:4] #view
np.may_share_memory(a,b)

True

####g

In [39]:
b=a #view
np.may_share_memory(a,b)

True

####h

In [40]:
b=a.copy() #copy
np.may_share_memory(a,b)

False

####i

In [41]:
b=np.random.choice(a,4) #copy
np.may_share_memory(a,b)

False

##9.3

###ex15

In [42]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

####a

In [43]:
print('size:' , a.size , ', shape:' , a.shape , ', ndim:' , a.ndim)

size: 12 , shape: (12,) , ndim: 1


####b

In [44]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [46]:
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [47]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

###ex16

In [48]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####a

In [49]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

####b

In [50]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

####c

In [51]:
a[:,np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

####d

In [52]:
b = a[:,np.newaxis].copy()
b.squeeze()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####e

In [53]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [54]:
a.swapaxes(0,1) #相等

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

####f

In [55]:
np.moveaxis(a,1,0) #相等

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

####g

In [56]:
np.split(a,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

####h

In [57]:
np.split(a,[1],axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

###ex17

In [58]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

####a

In [59]:
a[np.newaxis,:]

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

####b

In [60]:
a.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [61]:
a.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

####c

In [62]:
b.shape

(3, 1, 4)

In [63]:
np.moveaxis(a,2,0)

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [64]:
#swapaxes將軸0和軸2互換軸1不便，原本2*3*4變成4*3*2
#moveaxis將軸2移到軸0位置其他軸保持不變，原本2*3*4變成4*2*3

####d

In [65]:
np.split(a,2,axis=0)

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

####e

In [66]:
np.split(a,2,axis=2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

####f

In [67]:
np.vstack((a[0],a[1])) #垂直

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
np.hstack((a[0],a[1])) #水平

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

##10.1

###ex1

In [69]:
a = np.array([67.4, 76.1, 73.7, 84.9])

####a

In [70]:
np.sqrt(a)

array([8.2097503 , 8.7235314 , 8.58487041, 9.2141196 ])

####b

In [71]:
np.modf(a)[0]

array([0.4, 0.1, 0.7, 0.9])

####c

In [72]:
a[ np.floor(a) % 2 ==0]

array([76.1, 84.9])

####d

In [73]:
np.argmin(a,axis=0)

0

####e

In [74]:
a[a>70].mean()

78.23333333333333

###ex2

In [75]:
a = np.array([[5,12,8,14],
              [6,1,8,14],
              [21,17,3,0]])

####a

In [76]:
m = np.mean(a)
m

9.083333333333334

####b

In [77]:
np.mean(a[a>m])

15.6

####c

In [78]:
np.mean(a[a<=m])

4.428571428571429

####d

In [79]:
np.where(a>m,1,0)

array([[0, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0]])

###ex3

In [80]:
a = np.array([[12,10,0,9,12],
              [3,17,18,-3,3],
              [0,7,8,5,0]])

####a

In [81]:
np.max(a,axis=1)

array([12, 18,  8])

####b

In [82]:
np.argmin(a,axis=0)

array([2, 2, 0, 1, 2])

####c

In [83]:
np.sum(a,axis=1)

array([43, 38, 20])

####d

In [84]:
np.mean(a,axis=0)

array([ 5.        , 11.33333333,  8.66666667,  3.66666667,  5.        ])

####e

In [85]:
np.where(a==0)

(array([0, 2, 2]), array([2, 0, 4]))

####f

In [86]:
a[a>0].sum()

104

####g

In [87]:
np.where(a==a.max())

(array([1]), array([2]))

####h

In [88]:
a[:,np.all(a!=0,axis=0)]

array([[10,  9],
       [17, -3],
       [ 7,  5]])

####i

In [89]:
np.unique(a,axis=1)

array([[ 0,  9, 10, 12],
       [18, -3, 17,  3],
       [ 8,  5,  7,  0]])

####j

In [90]:
a[np.all(a!=5,axis=1),:]

array([[12, 10,  0,  9, 12],
       [ 3, 17, 18, -3,  3]])

In [91]:
a[:,np.all(a!=5,axis=0)]

array([[12, 10,  0, 12],
       [ 3, 17, 18,  3],
       [ 0,  7,  8,  0]])

####k

In [92]:
a[abs(a)==3].size

3

###ex4

####a

In [93]:
#(1,3)  (2,1)  (3,2)

####b

In [94]:
# 4 , 15 , 18 , 8

###ex5

In [95]:
a = np.array([[0,1,2,3,4],
              [2,3,4,0,1],
              [4,0,1,2,3],
              [1,2,3,4,0],
              [3,4,0,1,2]])

####a

In [96]:
r,c = 2,2
row,col = np.where(a==4)
dist = np.argmin((row-r)**2+(col-c)**2)
row[dist],col[dist]

(1, 2)

####b

In [97]:
r,c = 4,3
row,col = np.where(a==0)
dist = np.argmin((row-r)**2+(col-c)**2)
row[dist],col[dist]

(4, 2)

####c

In [98]:
r,c = 4,0
row,col = np.where(a==2)
dist = np.argmin((row-r)**2+(col-c)**2)
row[dist],col[dist]

(3, 1)

####d

In [99]:
row,col = np.where(a==4)
dist = np.zeros((len(row), len(row)))
for i in range(len(row)):
    for j in range(i + 1, len(row)):
        dist[i, j] = np.sqrt((row[i] - row[j])**2 + (col[i] - col[j])**2)
        dist[j, i] = dist[i, j]
max_dist_index = np.unravel_index(np.argmax(dist), dist.shape)
(row[max_dist_index[0]],col[max_dist_index[0]]),(row [max_dist_index[1]],col[max_dist_index[1]])

((0, 4), (4, 1))

####e

In [100]:
a[a==0].size

5

###ex6

In [101]:
def prime_list(n):
  prime = []
  for i in range(1,n):
    for j in range(2,i):
      if i % j == 0 :
        break
    else:
      prime.append(i)
  return prime

In [102]:
prime_list(30)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

###ex7

In [103]:
def find_pi(n):
    k=np.arange(0,n)
    return (1/16**k*(4/(8*k+1)-2/(8*k+4)-1/(8*k+5)-1/(8*k+6))).sum()

In [104]:
find_pi(2)

3.1414224664224664

##10.2

###ex8

In [105]:
a = np.array([12,7,23,76,23,77,54,33,98])

In [106]:
np.sort(a[a%2==0])

array([12, 54, 76, 98])

###ex9



In [119]:
a = np.array([[6, 4], [7, 1], [7, 4], [3, 8], [6, 9]])
points[np.argsort(np.sqrt(np.sum(a**2, axis=1)))]

array([[7, 1],
       [6, 4],
       [7, 4],
       [3, 8],
       [6, 9]])

###ex10

In [108]:
a = np.array([[5,16,12,1],
              [6,11,18,13],
              [2,7,3,8]])

####a

In [109]:
np.sort(a.flatten())

array([ 1,  2,  3,  5,  6,  7,  8, 11, 12, 13, 16, 18])

####b

In [110]:
np.sort(a,axis=1)

array([[ 1,  5, 12, 16],
       [ 6, 11, 13, 18],
       [ 2,  3,  7,  8]])

####c

In [111]:
a[np.argsort(a[:,0]),:]

array([[ 2,  7,  3,  8],
       [ 5, 16, 12,  1],
       [ 6, 11, 18, 13]])